project_id: "micyou"
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
base_url: "https://api.crowdin.com"

preserve_hierarchy: true

files:
  - source: /composeApp/src/commonMain/composeResources/files/i18n/strings_en.json
    translation: /composeApp/src/commonMain/composeResources/files/i18n/strings_%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        zh-CN: zh
        zh-TW: zh_tw
        zh-HK: zh_hk
        cat: cat
        ja: ja
        ko: ko
        fr: fr
        de: de
        es-ES: es
        ru: ru
        it: it
        pt-BR: pt
        ar: ar
        th: th
        vi: vi
        id: id
        tr: tr
        pl: pl
        nl: nl
