project_id: "micyou"
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
base_url: "https://api.crowdin.com"

preserve_hierarchy: true

files:
  - source: /composeApp/src/commonMain/composeResources/files/i18n/strings_en.json
    translation: /composeApp/src/commonMain/composeResources/files/i18n/strings_%locale%.json
    languages_mapping:
      locale:
        zh-CN: zh
        zh-TW: zh_tw
        en: en
