package com.lanrhyme.micyou

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.text.intl.Locale

enum class AppLanguage(val label: String, val code: String) {
    System("System / 跟随系统", "system"),
    Chinese("简体中文", "zh"),
    ChineseTraditional("繁體中文", "zh-TW"),
    English("English", "en")
}

data class AppStrings(
        val appName: String,
        val ipLabel: String,
        val portLabel: String,
        val targetIpLabel: String,
        val targetIpUsbLabel: String,
        val bluetoothAddressLabel: String,
        val connectionModeLabel: String,
        val modeWifi: String,
        val modeBluetooth: String,
        val modeUsb: String,
        val statusLabel: String,
        val statusIdle: String,
        val statusConnecting: String,
        val statusStreaming: String,
        val statusError: String,
        val muteLabel: String,
        val unmuteLabel: String,
        val micMuted: String,
        val micNormal: String,
        val settingsTitle: String,
        val close: String,
        val minimize: String,
        val start: String,
        val stop: String,
        val waitAdb: String,
        val usbAdbReverseHint: String,

        // Update
        val updateTitle: String,
        val updateMessage: String,
        val updateNow: String,
        val updateLater: String,
        val checkUpdate: String,
        val isLatestVersion: String,
        val checkingUpdate: String,

        // BlackHole (macOS virtual audio)
        val blackHoleInstalled: String,
        val blackHoleNotInstalled: String,
        val blackHoleInstallHint: String,
        val blackHoleConfigHint: String,
        val blackHoleNotFound: String,
        val blackHoleSwitchSuccess: String,
        val blackHoleSwitchFailed: String,
        val blackHoleRestored: String,
        val blackHoleUsingDevice: String,
        val blackHoleInitFailed: String,
        val blackHoleFallback: String,
        val blackHoleTrying: String,

        // Install progress messages
        val installOsNotSupported: String,
        val installCheckingPackage: String,
        val installDownloading: String,
        val installDownloadFailed: String,
        val installInstalling: String,
        val installConfiguring: String,
        val installConfigComplete: String,
        val installNotCompleted: String,
        val installError: String,
        val installCheckingLinux: String,
        val installLinuxExists: String,
        val installCreatingDevice: String,
        val installDeviceCreated: String,
        val installDeviceFailed: String,

        // Settings
        val generalSection: String,
        val appearanceSection: String,
        val audioSection: String,
        val aboutSection: String,
        val languageLabel: String,
        val themeLabel: String,
        val themeSystem: String,
        val themeLight: String,
        val themeDark: String,
        val autoStartLabel: String,
        val monitoringLabel: String,
        val sampleRateLabel: String,
        val channelCountLabel: String,
        val audioFormatLabel: String,
        val enableNsLabel: String,
        val nsTypeLabel: String,
        val nsAlgorithmHelpTitle: String,
        val nsAlgorithmCloseButton: String,
        val nsAlgorithmRNNoiseTitle: String,
        val nsAlgorithmRNNoiseDesc: String,
        val nsAlgorithmUlnasTitle: String,
        val nsAlgorithmUlnasDesc: String,
        val nsAlgorithmSpeexdspTitle: String,
        val nsAlgorithmSpeexdspDesc: String,
        val nsAlgorithmRecommended: String,
        val nsAlgorithmAlternative: String,
        val nsAlgorithmLightweight: String,
        val enableAgcLabel: String,
        val agcTargetLabel: String,
        val enableVadLabel: String,
        val vadThresholdLabel: String,
        val audioConfigAppliedLabel: String,
        val enableDereverbLabel: String,
        val dereverbLevelLabel: String,
        val amplificationLabel: String,
        val openSourceLicense: String,
        val viewLibraries: String,
        val softwareIntro: String,
        val introText: String,
        val systemConfigTitle: String,
        val enableStreamingNotificationLabel: String,

        // Missing keys
        val clickToStart: String,
        val autoStartDesc: String,
        val noGeneralSettings: String,
        val themeColorLabel: String,
        val amplificationMultiplierLabel: String,
        val licensesTitle: String,
        val basedOnAndroidMic: String,
        val developerLabel: String,
        val githubRepoLabel: String,
        val versionLabel: String,
        val useDynamicColorLabel: String,
        val androidAudioProcessingLabel: String,
        val androidAudioProcessingDesc: String,
        val contributorsLabel: String,
        val contributorsDesc: String,
        val autoConfigLabel: String,
        val autoConfigDesc: String,
        val logsSection: String,
        val exportLog: String,
        val exportLogDesc: String,
        val logExported: String,
        val logExportFailed: String,
        val firewallTitle: String,
        val firewallMessage: String,
        val firewallConfirm: String,
        val firewallDismiss: String,
        val trayShow: String,
        val trayHide: String,
        val trayExit: String,
        val minimizeToTrayLabel: String,
        val closeConfirmTitle: String,
        val closeConfirmMessage: String,
        val closeConfirmMinimize: String,
        val closeConfirmExit: String,
        val closeConfirmRemember: String,
        val closeActionLabel: String,
        val closeActionPrompt: String,
        val closeActionMinimize: String,
        val closeActionExit: String
)

val EnStrings =
        AppStrings(
                appName = "MicYou",
                ipLabel = "IP: ",
                portLabel = "Port",
                targetIpLabel = "Target IP",
                targetIpUsbLabel = "Target IP (127.0.0.1)",
                bluetoothAddressLabel = "Bluetooth Device Address (MAC)",
                connectionModeLabel = "Connection Mode",
                modeWifi = "Wi-Fi",
                modeBluetooth = "Bluetooth",
                modeUsb = "USB",
                statusLabel = "Status: ",
                statusIdle = "Idle",
                statusConnecting = "Connecting...",
                statusStreaming = "Streaming",
                statusError = "Error",
                muteLabel = "Mute",
                unmuteLabel = "Unmute",
                micMuted = "Microphone Muted",
                micNormal = "Microphone Normal",
                settingsTitle = "Settings",
                close = "Close",
                minimize = "Minimize",
                start = "Start",
                stop = "Stop",
                waitAdb = "Waiting for ADB connection...",
                usbAdbReverseHint = "Run on PC:",
                generalSection = "General",
                appearanceSection = "Appearance",
                audioSection = "Audio",
                aboutSection = "About",
                languageLabel = "Language",
                themeLabel = "Theme Mode",
                themeSystem = "System",
                themeLight = "Light",
                themeDark = "Dark",
                autoStartLabel = "Auto Start",
                monitoringLabel = "Monitoring (Desktop)",
                sampleRateLabel = "Sample Rate",
                channelCountLabel = "Channels",
                audioFormatLabel = "Audio Format",
                enableNsLabel = "Noise Suppression",
                nsTypeLabel = "Algorithm",
                nsAlgorithmHelpTitle = "Noise Reduction Algorithms",
                nsAlgorithmCloseButton = "Got it",
                nsAlgorithmRNNoiseTitle = "RNNoise",
                nsAlgorithmRNNoiseDesc =
                        "Deep learning-based noise reduction algorithm with the best results. Intelligently identifies and eliminates various background noises while maintaining voice clarity. Suitable for most scenarios.",
                nsAlgorithmUlnasTitle = "Ulunas (ONNX)",
                nsAlgorithmUlnasDesc =
                        "ONNX Runtime-based noise reduction model providing good noise reduction effects. Better than RNNoise in some cases, but may not work on some devices or systems.",
                nsAlgorithmSpeexdspTitle = "Speexdsp",
                nsAlgorithmSpeexdspDesc =
                        "Traditional digital signal processing algorithm, lightweight and requires no additional models. Basic noise reduction effect, suitable for low-performance devices or latency-sensitive scenarios.",
                nsAlgorithmRecommended = "Recommended",
                nsAlgorithmAlternative = "Alternative",
                nsAlgorithmLightweight = "Lightweight",
                enableAgcLabel = "AGC",
                agcTargetLabel = "Target Level",
                enableVadLabel = "VAD",
                vadThresholdLabel = "Sensitivity",
                audioConfigAppliedLabel = "Applied",
                enableDereverbLabel = "Dereverb",
                dereverbLevelLabel = "Level",
                amplificationLabel = "Amplification",
                openSourceLicense = "License",
                viewLibraries = "View Open Source Libraries",
                softwareIntro = "Introduction",
                introText =
                        "MicYou is an open source microphone tool that turns your Android device into a high-quality microphone for your computer. Based on AndroidMic, it supports Wi-Fi (TCP), Bluetooth, and USB connections, providing low-latency audio transmission.",
                systemConfigTitle = "System Configuration",
                enableStreamingNotificationLabel = "Streaming Notification (Android)",
                clickToStart = "Click to Start",
                autoStartDesc = "Start streaming automatically on app launch",
                noGeneralSettings = "No general settings available",
                themeColorLabel = "Theme Color",
                amplificationMultiplierLabel = "Multiplier",
                licensesTitle = "Open Source Libraries and Licenses",
                basedOnAndroidMic = "MicYou is based on AndroidMic.",
                developerLabel = "Developer",
                githubRepoLabel = "GitHub Repository",
                versionLabel = "Version",
                useDynamicColorLabel = "Use System Dynamic Color",
                androidAudioProcessingLabel = "Built-in Audio Processing",
                androidAudioProcessingDesc =
                        "Use hardware audio processing. May affect output quality.",
                contributorsLabel = "Contributors",
                contributorsDesc = "Thanks to everyone who contributed to this project.",
                autoConfigLabel = "Auto Configure Audio",
                autoConfigDesc =
                        "Automatically select optimal audio settings based on connection mode",
                logsSection = "Logs",
                exportLog = "Export Log",
                exportLogDesc = "Export application logs for debugging",
                logExported = "Log exported to: %s",
                logExportFailed = "Failed to export log",
                firewallTitle = "Firewall Check",
                firewallMessage =
                        "Port %d is not allowed by Windows Firewall. This may prevent Android devices from connecting via Wi-Fi.\n\nWould you like to try adding a firewall rule for this port? (Requires Administrator privileges)",
                firewallConfirm = "Try Add Rule",
                firewallDismiss = "Ignore",
                trayShow = "Show App",
                trayHide = "Hide App",
                trayExit = "Exit",
                minimizeToTrayLabel = "Minimize to Tray on Close",
                closeConfirmTitle = "Close Confirmation",
                closeConfirmMessage = "What would you like to do when closing the application?",
                closeConfirmMinimize = "Minimize to Tray",
                closeConfirmExit = "Exit Application",
                closeConfirmRemember = "Don't ask again",
                closeActionLabel = "Close Button Action",
                closeActionPrompt = "Ask every time",
                closeActionMinimize = "Minimize to Tray",
                closeActionExit = "Exit Application",

                // Update
                updateTitle = "New Version Available",
                updateMessage =
                        "A new version (%s) is available on GitHub. Would you like to update now?",
                updateNow = "Update Now",
                updateLater = "Later",
                checkUpdate = "Check for Updates",
                isLatestVersion = "Already the latest version",
                checkingUpdate = "Checking for updates...",

                // BlackHole (macOS virtual audio)
                blackHoleInstalled = "BlackHole is installed, please configure in System Settings",
                blackHoleNotInstalled = "Please install BlackHole virtual audio driver manually",
                blackHoleInstallHint = "Installation guide: existential.audio/blackhole/",
                blackHoleConfigHint = "BlackHole installed, please configure in System Settings",
                blackHoleNotFound = "Cannot find BlackHole virtual input device",
                blackHoleSwitchSuccess = "Successfully switched to BlackHole",
                blackHoleSwitchFailed = "Failed to switch to BlackHole",
                blackHoleRestored = "Restored to original device",
                blackHoleUsingDevice = "Using BlackHole device: %s",
                blackHoleInitFailed = "Failed to initialize BlackHole",
                blackHoleFallback = "BlackHole not found, falling back to default device",
                blackHoleTrying = "macOS: Trying to use BlackHole virtual device",

                // Install progress
                installOsNotSupported = "Auto-install not supported for current OS",
                installCheckingPackage = "Checking installer...",
                installDownloading = "Downloading VB-Cable driver...",
                installDownloadFailed = "Download failed: cannot find or download driver",
                installInstalling = "Installing VB-Cable driver...",
                installConfiguring = "Configuring...",
                installConfigComplete = "Configuration complete",
                installNotCompleted = "Installation not completed or cancelled",
                installError = "Installation error: %s",
                installCheckingLinux = "Checking Linux audio system...",
                installLinuxExists = "Virtual audio device exists, configuring...",
                installCreatingDevice = "Creating virtual audio device...",
                installDeviceCreated = "Virtual device created, configuring...",
                installDeviceFailed = "Virtual device creation failed, check system permissions and audio service"
        )

val ZhStrings =
        AppStrings(
                appName = "MicYou",
                ipLabel = "IP: ",
                portLabel = "端口",
                targetIpLabel = "目标 IP",
                targetIpUsbLabel = "目标 IP (127.0.0.1)",
                bluetoothAddressLabel = "蓝牙设备地址 (MAC)",
                connectionModeLabel = "连接模式",
                modeWifi = "Wi-Fi",
                modeBluetooth = "蓝牙",
                modeUsb = "USB",
                statusLabel = "状态: ",
                statusIdle = "空闲",
                statusConnecting = "连接中...",
                statusStreaming = "正在传输",
                statusError = "错误",
                muteLabel = "静音",
                unmuteLabel = "取消静音",
                micMuted = "麦克风已静音",
                micNormal = "麦克风正常",
                settingsTitle = "设置",
                close = "关闭",
                minimize = "最小化",
                start = "开始",
                stop = "停止",
                waitAdb = "等待 ADB 连接...",
                usbAdbReverseHint = "在电脑端执行：",
                generalSection = "通用",
                appearanceSection = "外观",
                audioSection = "音频",
                aboutSection = "关于",
                languageLabel = "语言",
                themeLabel = "主题模式",
                themeSystem = "跟随系统",
                themeLight = "亮色",
                themeDark = "暗色",
                autoStartLabel = "自动串流",
                monitoringLabel = "监听 (仅桌面)",
                sampleRateLabel = "采样率",
                channelCountLabel = "通道数",
                audioFormatLabel = "音频格式",
                enableNsLabel = "降噪 (Noise Suppression)",
                nsTypeLabel = "降噪算法",
                nsAlgorithmHelpTitle = "降噪算法说明",
                nsAlgorithmCloseButton = "知道了",
                nsAlgorithmRNNoiseTitle = "RNNoise",
                nsAlgorithmRNNoiseDesc = "基于深度学习的降噪算法，效果最佳。能够智能识别并消除各种背景噪音，同时保持语音清晰度。适合大多数使用场景。",
                nsAlgorithmUlnasTitle = "Ulunas (ONNX)",
                nsAlgorithmUlnasDesc =
                        "基于 ONNX Runtime 的降噪模型，提供较好的降噪效果。相比于RNNoise更加优秀，但在部分设备或系统中可能无法使用。",
                nsAlgorithmSpeexdspTitle = "Speexdsp",
                nsAlgorithmSpeexdspDesc = "传统的数字信号处理算法，轻量级且无需额外模型。降噪效果较基础，适合低性能设备或对延迟敏感的场景。",
                nsAlgorithmRecommended = "推荐",
                nsAlgorithmAlternative = "备选",
                nsAlgorithmLightweight = "轻量",
                enableAgcLabel = "自动增益控制 (AGC)",
                agcTargetLabel = "目标电平",
                enableVadLabel = "语音活动检测 (VAD)",
                vadThresholdLabel = "灵敏度",
                audioConfigAppliedLabel = "已应用",
                enableDereverbLabel = "去混响 (Dereverb)",
                dereverbLevelLabel = "强度",
                amplificationLabel = "信号放大 (Amplification)",
                openSourceLicense = "开源许可",
                viewLibraries = "查看使用的开源库",
                softwareIntro = "软件介绍",
                introText =
                        "MicYou 是一款开源的麦克风工具，可以将您的 Android 设备变成电脑的高质量麦克风，本软件基于 AndroidMic 进行开发，支持 Wi-Fi (TCP)、蓝牙 和 USB 连接，提供低延迟的音频传输体验。",
                systemConfigTitle = "系统配置中",
                enableStreamingNotificationLabel = "串流通知 (Android)",
                clickToStart = "点击开始",
                autoStartDesc = "应用启动时自动开始串流",
                noGeneralSettings = "暂无通用设置",
                themeColorLabel = "主题颜色",
                amplificationMultiplierLabel = "倍数",
                licensesTitle = "Open Source Libraries and Licenses",
                basedOnAndroidMic = "MicYou 基于 AndroidMic 项目开发。",
                developerLabel = "开发者",
                githubRepoLabel = "Github 仓库",
                versionLabel = "版本",
                useDynamicColorLabel = "使用系统动态颜色(莫奈取色)",
                androidAudioProcessingLabel = "手机硬件内置音频处理",
                androidAudioProcessingDesc = "开启后可能会影响输出的最终效果",
                contributorsLabel = "贡献者",
                contributorsDesc = "感谢每一位为本项目做出贡献的人",
                autoConfigLabel = "自动配置音频",
                autoConfigDesc = "根据连接模式自动选择最佳音频设置",
                logsSection = "日志",
                exportLog = "导出日志",
                exportLogDesc = "导出应用日志以供调试",
                logExported = "日志已导出至: %s",
                logExportFailed = "导出日志失败",
                firewallTitle = "防火墙检查",
                firewallMessage =
                        "端口 %d 似乎未被 Windows 防火墙放行。这可能会导致 Android 设备无法通过 Wi-Fi 连接。\n\n是否尝试自动添加防火墙规则？（需要管理员权限）",
                firewallConfirm = "尝试添加",
                firewallDismiss = "忽略",
                trayShow = "显示应用",
                trayHide = "隐藏应用",
                trayExit = "退出",
                minimizeToTrayLabel = "关闭时最小化到托盘",
                closeConfirmTitle = "退出确认",
                closeConfirmMessage = "关闭应用时，您想执行什么操作？",
                closeConfirmMinimize = "最小化到托盘",
                closeConfirmExit = "直接退出应用",
                closeConfirmRemember = "不再提示",
                closeActionLabel = "关闭按钮操作",
                closeActionPrompt = "每次询问",
                closeActionMinimize = "最小化到托盘",
                closeActionExit = "直接退出",

                // Update
                updateTitle = "发现新版本",
                updateMessage = "GitHub 上有新版本 (%s) 可用。是否立即前往更新？",
                updateNow = "立即更新",
                updateLater = "稍后",
                checkUpdate = "检查更新",
                isLatestVersion = "当前已是最新版本",
                checkingUpdate = "正在检查更新...",

                // BlackHole (macOS virtual audio)
                blackHoleInstalled = "BlackHole 已安装，请在系统设置中配置",
                blackHoleNotInstalled = "请手动安装 BlackHole 虚拟音频驱动",
                blackHoleInstallHint = "安装说明: existential.audio/blackhole/",
                blackHoleConfigHint = "BlackHole 已安装，请在系统设置中配置",
                blackHoleNotFound = "无法找到 BlackHole 虚拟输入设备",
                blackHoleSwitchSuccess = "已切换到 BlackHole",
                blackHoleSwitchFailed = "切换到 BlackHole 失败",
                blackHoleRestored = "已恢复原始设备",
                blackHoleUsingDevice = "正在使用 BlackHole 设备: %s",
                blackHoleInitFailed = "初始化 BlackHole 失败",
                blackHoleFallback = "未找到 BlackHole，回退到默认设备",
                blackHoleTrying = "macOS: 尝试使用 BlackHole 虚拟设备",

                // Install progress
                installOsNotSupported = "当前操作系统不支持自动安装虚拟音频设备",
                installCheckingPackage = "正在检查安装包...",
                installDownloading = "正在下载 VB-Cable 驱动...",
                installDownloadFailed = "安装失败：无法下载或找到驱动",
                installInstalling = "正在安装 VB-Cable 驱动...",
                installConfiguring = "正在配置...",
                installConfigComplete = "配置完成",
                installNotCompleted = "安装未完成或被取消",
                installError = "安装错误: %s",
                installCheckingLinux = "正在检查Linux音频系统...",
                installLinuxExists = "虚拟音频设备已存在，正在配置...",
                installCreatingDevice = "正在创建虚拟音频设备...",
                installDeviceCreated = "虚拟设备创建成功，正在配置...",
                installDeviceFailed = "虚拟设备创建失败，请检查系统权限和音频服务"
        )

val ZhTwStrings =
        AppStrings(
                appName = "MicYou",
                ipLabel = "IP: ",
                portLabel = "連接埠",
                targetIpLabel = "目標 IP",
                targetIpUsbLabel = "目標 IP (127.0.0.1)",
                bluetoothAddressLabel = "藍牙裝置位址 (MAC)",
                connectionModeLabel = "連線模式",
                modeWifi = "Wi-Fi",
                modeBluetooth = "藍牙",
                modeUsb = "USB",
                statusLabel = "狀態: ",
                statusIdle = "閒置",
                statusConnecting = "連線中...",
                statusStreaming = "傳輸中",
                statusError = "錯誤",
                muteLabel = "靜音",
                unmuteLabel = "取消靜音",
                micMuted = "麥克風已靜音",
                micNormal = "麥克風正常",
                settingsTitle = "設定",
                close = "關閉",
                minimize = "最小化",
                start = "開始",
                stop = "停止",
                waitAdb = "等待 ADB 連線...",
                usbAdbReverseHint = "在電腦端執行：",
                generalSection = "一般",
                appearanceSection = "外觀",
                audioSection = "音訊",
                aboutSection = "關於",
                languageLabel = "語言",
                themeLabel = "主題模式",
                themeSystem = "跟隨系統",
                themeLight = "亮色",
                themeDark = "暗色",
                autoStartLabel = "自動串流",
                monitoringLabel = "監聽 (僅桌面)",
                sampleRateLabel = "取樣率",
                channelCountLabel = "聲道數",
                audioFormatLabel = "音訊格式",
                enableNsLabel = "降噪 (Noise Suppression)",
                nsTypeLabel = "降噪演算法",
                nsAlgorithmHelpTitle = "降噪演算法說明",
                nsAlgorithmCloseButton = "知道了",
                nsAlgorithmRNNoiseTitle = "RNNoise",
                nsAlgorithmRNNoiseDesc = "基於深度學習的降噪演算法，效果最佳。能夠智慧識別並消除各種背景噪音，同時保持語音清晰度。適合大多數使用場景。",
                nsAlgorithmUlnasTitle = "Ulunas (ONNX)",
                nsAlgorithmUlnasDesc =
                        "基於 ONNX Runtime 的降噪模型，提供較好的降噪效果。相比於 RNNoise 更加優秀，但在部分裝置或系統中可能無法使用。",
                nsAlgorithmSpeexdspTitle = "Speexdsp",
                nsAlgorithmSpeexdspDesc = "傳統的數位訊號處理演算法，輕量級且無需額外模型。降噪效果較基礎，適合低效能裝置或對延遲敏感的場景。",
                nsAlgorithmRecommended = "推薦",
                nsAlgorithmAlternative = "備選",
                nsAlgorithmLightweight = "輕量",
                enableAgcLabel = "自動增益控制 (AGC)",
                agcTargetLabel = "目標電平",
                enableVadLabel = "語音活動偵測 (VAD)",
                vadThresholdLabel = "靈敏度",
                audioConfigAppliedLabel = "已套用",
                enableDereverbLabel = "去混響 (Dereverb)",
                dereverbLevelLabel = "強度",
                amplificationLabel = "訊號放大 (Amplification)",
                openSourceLicense = "開源授權",
                viewLibraries = "查看使用的開源函式庫",
                softwareIntro = "軟體介紹",
                introText =
                        "MicYou 是一款開源的麥克風工具，可以將您的 Android 裝置變成電腦的高品質麥克風，本軟體基於 AndroidMic 進行開發，支援 Wi-Fi (TCP)、藍牙 和 USB 連線，提供低延遲的音訊傳輸體驗。",
                systemConfigTitle = "系統設定中",
                enableStreamingNotificationLabel = "串流通知 (Android)",
                clickToStart = "點擊開始",
                autoStartDesc = "應用啟動時自動開始串流",
                noGeneralSettings = "暫無一般設定",
                themeColorLabel = "主題顏色",
                amplificationMultiplierLabel = "倍數",
                licensesTitle = "開源函式庫與授權",
                basedOnAndroidMic = "MicYou 基於 AndroidMic 專案開發。",
                developerLabel = "開發者",
                githubRepoLabel = "GitHub 儲存庫",
                versionLabel = "版本",
                useDynamicColorLabel = "使用系統動態顏色（莫內取色）",
                androidAudioProcessingLabel = "手機硬體內建音訊處理",
                androidAudioProcessingDesc = "開啟後可能會影響輸出的最終效果",
                contributorsLabel = "貢獻者",
                contributorsDesc = "感謝每一位為本專案做出貢獻的人",
                autoConfigLabel = "自動配置音訊",
                autoConfigDesc = "根據連線模式自動選擇最佳音訊設定",
                logsSection = "日誌",
                exportLog = "匯出日誌",
                exportLogDesc = "匯出應用程式日誌以供除錯",
                logExported = "日誌已匯出至: %s",
                logExportFailed = "匯出日誌失敗",
                firewallTitle = "防火牆檢查",
                firewallMessage =
                        "連接埠 %d 似乎未被 Windows 防火牆放行。這可能會導致 Android 裝置無法透過 Wi-Fi 連線。\n\n是否嘗試自動新增防火牆規則？（需要系統管理員權限）",
                firewallConfirm = "嘗試新增",
                firewallDismiss = "忽略",
                trayShow = "顯示應用程式",
                trayHide = "隱藏應用程式",
                trayExit = "結束",
                minimizeToTrayLabel = "關閉時最小化到托盤",
                closeConfirmTitle = "關閉確認",
                closeConfirmMessage = "關閉應用程式時，您想執行什麼操作？",
                closeConfirmMinimize = "最小化到托盤",
                closeConfirmExit = "直接結束應用程式",
                closeConfirmRemember = "不再提示",
                closeActionLabel = "關閉按鈕操作",
                closeActionPrompt = "每次詢問",
                closeActionMinimize = "最小化到托盤",
                closeActionExit = "直接結束",

                // Update
                updateTitle = "發現新版本",
                updateMessage = "GitHub 上有新版本 (%s) 可用。是否立即前往更新？",
                updateNow = "立即更新",
                updateLater = "稍後",
                checkUpdate = "檢查更新",
                isLatestVersion = "目前已是最新版本",
                checkingUpdate = "正在檢查更新...",

                // BlackHole (macOS virtual audio)
                blackHoleInstalled = "BlackHole 已安裝，請在系統設定中配置",
                blackHoleNotInstalled = "請手動安裝 BlackHole 虛擬音訊驅動",
                blackHoleInstallHint = "安裝說明: existential.audio/blackhole/",
                blackHoleConfigHint = "BlackHole 已安裝，請在系統設定中配置",
                blackHoleNotFound = "無法找到 BlackHole 虛擬輸入設備",
                blackHoleSwitchSuccess = "已切換到 BlackHole",
                blackHoleSwitchFailed = "切換到 BlackHole 失敗",
                blackHoleRestored = "已恢復原始設備",
                blackHoleUsingDevice = "正在使用 BlackHole 設備: %s",
                blackHoleInitFailed = "初始化 BlackHole 失敗",
                blackHoleFallback = "未找到 BlackHole，回退到默認設備",
                blackHoleTrying = "macOS: 嘗試使用 BlackHole 虛擬設備",

                // Install progress
                installOsNotSupported = "當前操作系統不支援自動安裝虛擬音訊設備",
                installCheckingPackage = "正在檢查安裝包...",
                installDownloading = "正在下載 VB-Cable 驅動...",
                installDownloadFailed = "安裝失敗：無法下載或找到驅動",
                installInstalling = "正在安裝 VB-Cable 驅動...",
                installConfiguring = "正在配置...",
                installConfigComplete = "配置完成",
                installNotCompleted = "安裝未完成或被取消",
                installError = "安裝錯誤: %s",
                installCheckingLinux = "正在檢查Linux音訊系統...",
                installLinuxExists = "虛擬音訊設備已存在，正在配置...",
                installCreatingDevice = "正在創建虛擬音訊設備...",
                installDeviceCreated = "虛擬設備創建成功，正在配置...",
                installDeviceFailed = "虛擬設備創建失敗，請檢查系統權限和音訊服務"
        )

val LocalAppStrings = staticCompositionLocalOf { ZhStrings }

fun getStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.Chinese -> ZhStrings
        AppLanguage.ChineseTraditional -> ZhTwStrings
        AppLanguage.English -> EnStrings
        AppLanguage.System -> {
            val locale = Locale.current.language
            if (locale.startsWith("zh")) ZhStrings else EnStrings
        }
    }
}
